name: CI
permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.1'   # >=20.12.0 都可以；推荐 LTS 22
          check-latest: true
          cache: 'npm'

      - run: node -v && which node
      - run: node -p "process.versions"   # 再次确认版本，避免走到旧 Node
      - run: npm ci
      - run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.8
        with:
          branch: gh-pages
          folder: dist